tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "ngrok/ngrok"
brew "cmake"
brew "git"
brew "go"
brew "neovim"
brew "node"
brew "openjdk"
brew "python@3.9"
brew "vim", args: ["HEAD"]
cask "graphql-playground"
cask "keepassxc"
cask "ngrok"
